import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { BehaviorSubject, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class LangService {
  private directionSubject = new BehaviorSubject<any>('ltr');
  direction$ = this.directionSubject.asObservable();
  private countries = new BehaviorSubject<any>([
    { name: 'Afghanistan', code: 'AF' },
    { name: 'land Islands', code: 'AX' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'AndorrA', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, The Democratic Republic of the', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Cote DIvoire', code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { name: 'Holy See (Vatican City State)', code: 'VA' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic Of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Korea, Democratic PeopleS Republic of', code: 'KP' },
    { name: 'Korea, Republic of', code: 'KR' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Lao PeopleS Democratic Republic', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macao', code: 'MO' },
    { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'RWANDA', code: 'RW' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia', code: 'RS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },
    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.S.', code: 'VI' },
    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' },
  ]);
  countries$ = this.countries.asObservable();
  constructor(private translate: TranslateService, private _router: Router) {
    this.translate.setDefaultLang('en');
    this.translate.use('en');
  }
  changeLang(lang: string, dir: string) {
    this.translate.use(lang);
    if (lang == 'en') {
      this.directionSubject.next(dir);
      this.countries.next([
        { name: 'Afghanistan', code: 'AF' },
        { name: 'land Islands', code: 'AX' },
        { name: 'Albania', code: 'AL' },
        { name: 'Algeria', code: 'DZ' },
        { name: 'American Samoa', code: 'AS' },
        { name: 'AndorrA', code: 'AD' },
        { name: 'Angola', code: 'AO' },
        { name: 'Anguilla', code: 'AI' },
        { name: 'Antarctica', code: 'AQ' },
        { name: 'Antigua and Barbuda', code: 'AG' },
        { name: 'Argentina', code: 'AR' },
        { name: 'Armenia', code: 'AM' },
        { name: 'Aruba', code: 'AW' },
        { name: 'Australia', code: 'AU' },
        { name: 'Austria', code: 'AT' },
        { name: 'Azerbaijan', code: 'AZ' },
        { name: 'Bahamas', code: 'BS' },
        { name: 'Bahrain', code: 'BH' },
        { name: 'Bangladesh', code: 'BD' },
        { name: 'Barbados', code: 'BB' },
        { name: 'Belarus', code: 'BY' },
        { name: 'Belgium', code: 'BE' },
        { name: 'Belize', code: 'BZ' },
        { name: 'Benin', code: 'BJ' },
        { name: 'Bermuda', code: 'BM' },
        { name: 'Bhutan', code: 'BT' },
        { name: 'Bolivia', code: 'BO' },
        { name: 'Bosnia and Herzegovina', code: 'BA' },
        { name: 'Botswana', code: 'BW' },
        { name: 'Bouvet Island', code: 'BV' },
        { name: 'Brazil', code: 'BR' },
        { name: 'British Indian Ocean Territory', code: 'IO' },
        { name: 'Brunei Darussalam', code: 'BN' },
        { name: 'Bulgaria', code: 'BG' },
        { name: 'Burkina Faso', code: 'BF' },
        { name: 'Burundi', code: 'BI' },
        { name: 'Cambodia', code: 'KH' },
        { name: 'Cameroon', code: 'CM' },
        { name: 'Canada', code: 'CA' },
        { name: 'Cape Verde', code: 'CV' },
        { name: 'Cayman Islands', code: 'KY' },
        { name: 'Central African Republic', code: 'CF' },
        { name: 'Chad', code: 'TD' },
        { name: 'Chile', code: 'CL' },
        { name: 'China', code: 'CN' },
        { name: 'Christmas Island', code: 'CX' },
        { name: 'Cocos (Keeling) Islands', code: 'CC' },
        { name: 'Colombia', code: 'CO' },
        { name: 'Comoros', code: 'KM' },
        { name: 'Congo', code: 'CG' },
        { name: 'Congo, The Democratic Republic of the', code: 'CD' },
        { name: 'Cook Islands', code: 'CK' },
        { name: 'Costa Rica', code: 'CR' },
        { name: 'Cote DIvoire', code: 'CI' },
        { name: 'Croatia', code: 'HR' },
        { name: 'Cuba', code: 'CU' },
        { name: 'Cyprus', code: 'CY' },
        { name: 'Czech Republic', code: 'CZ' },
        { name: 'Denmark', code: 'DK' },
        { name: 'Djibouti', code: 'DJ' },
        { name: 'Dominica', code: 'DM' },
        { name: 'Dominican Republic', code: 'DO' },
        { name: 'Ecuador', code: 'EC' },
        { name: 'Egypt', code: 'EG' },
        { name: 'El Salvador', code: 'SV' },
        { name: 'Equatorial Guinea', code: 'GQ' },
        { name: 'Eritrea', code: 'ER' },
        { name: 'Estonia', code: 'EE' },
        { name: 'Ethiopia', code: 'ET' },
        { name: 'Falkland Islands (Malvinas)', code: 'FK' },
        { name: 'Faroe Islands', code: 'FO' },
        { name: 'Fiji', code: 'FJ' },
        { name: 'Finland', code: 'FI' },
        { name: 'France', code: 'FR' },
        { name: 'French Guiana', code: 'GF' },
        { name: 'French Polynesia', code: 'PF' },
        { name: 'French Southern Territories', code: 'TF' },
        { name: 'Gabon', code: 'GA' },
        { name: 'Gambia', code: 'GM' },
        { name: 'Georgia', code: 'GE' },
        { name: 'Germany', code: 'DE' },
        { name: 'Ghana', code: 'GH' },
        { name: 'Gibraltar', code: 'GI' },
        { name: 'Greece', code: 'GR' },
        { name: 'Greenland', code: 'GL' },
        { name: 'Grenada', code: 'GD' },
        { name: 'Guadeloupe', code: 'GP' },
        { name: 'Guam', code: 'GU' },
        { name: 'Guatemala', code: 'GT' },
        { name: 'Guernsey', code: 'GG' },
        { name: 'Guinea', code: 'GN' },
        { name: 'Guinea-Bissau', code: 'GW' },
        { name: 'Guyana', code: 'GY' },
        { name: 'Haiti', code: 'HT' },
        { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
        { name: 'Holy See (Vatican City State)', code: 'VA' },
        { name: 'Honduras', code: 'HN' },
        { name: 'Hong Kong', code: 'HK' },
        { name: 'Hungary', code: 'HU' },
        { name: 'Iceland', code: 'IS' },
        { name: 'India', code: 'IN' },
        { name: 'Indonesia', code: 'ID' },
        { name: 'Iran, Islamic Republic Of', code: 'IR' },
        { name: 'Iraq', code: 'IQ' },
        { name: 'Ireland', code: 'IE' },
        { name: 'Isle of Man', code: 'IM' },
        { name: 'Israel', code: 'IL' },
        { name: 'Italy', code: 'IT' },
        { name: 'Jamaica', code: 'JM' },
        { name: 'Japan', code: 'JP' },
        { name: 'Jersey', code: 'JE' },
        { name: 'Jordan', code: 'JO' },
        { name: 'Kazakhstan', code: 'KZ' },
        { name: 'Kenya', code: 'KE' },
        { name: 'Kiribati', code: 'KI' },
        { name: 'Korea, Democratic PeopleS Republic of', code: 'KP' },
        { name: 'Korea, Republic of', code: 'KR' },
        { name: 'Kuwait', code: 'KW' },
        { name: 'Kyrgyzstan', code: 'KG' },
        { name: 'Lao PeopleS Democratic Republic', code: 'LA' },
        { name: 'Latvia', code: 'LV' },
        { name: 'Lebanon', code: 'LB' },
        { name: 'Lesotho', code: 'LS' },
        { name: 'Liberia', code: 'LR' },
        { name: 'Libyan Arab Jamahiriya', code: 'LY' },
        { name: 'Liechtenstein', code: 'LI' },
        { name: 'Lithuania', code: 'LT' },
        { name: 'Luxembourg', code: 'LU' },
        { name: 'Macao', code: 'MO' },
        { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
        { name: 'Madagascar', code: 'MG' },
        { name: 'Malawi', code: 'MW' },
        { name: 'Malaysia', code: 'MY' },
        { name: 'Maldives', code: 'MV' },
        { name: 'Mali', code: 'ML' },
        { name: 'Malta', code: 'MT' },
        { name: 'Marshall Islands', code: 'MH' },
        { name: 'Martinique', code: 'MQ' },
        { name: 'Mauritania', code: 'MR' },
        { name: 'Mauritius', code: 'MU' },
        { name: 'Mayotte', code: 'YT' },
        { name: 'Mexico', code: 'MX' },
        { name: 'Micronesia, Federated States of', code: 'FM' },
        { name: 'Moldova, Republic of', code: 'MD' },
        { name: 'Monaco', code: 'MC' },
        { name: 'Mongolia', code: 'MN' },
        { name: 'Montenegro', code: 'ME' },
        { name: 'Montserrat', code: 'MS' },
        { name: 'Morocco', code: 'MA' },
        { name: 'Mozambique', code: 'MZ' },
        { name: 'Myanmar', code: 'MM' },
        { name: 'Namibia', code: 'NA' },
        { name: 'Nauru', code: 'NR' },
        { name: 'Nepal', code: 'NP' },
        { name: 'Netherlands', code: 'NL' },
        { name: 'Netherlands Antilles', code: 'AN' },
        { name: 'New Caledonia', code: 'NC' },
        { name: 'New Zealand', code: 'NZ' },
        { name: 'Nicaragua', code: 'NI' },
        { name: 'Niger', code: 'NE' },
        { name: 'Nigeria', code: 'NG' },
        { name: 'Niue', code: 'NU' },
        { name: 'Norfolk Island', code: 'NF' },
        { name: 'Northern Mariana Islands', code: 'MP' },
        { name: 'Norway', code: 'NO' },
        { name: 'Oman', code: 'OM' },
        { name: 'Pakistan', code: 'PK' },
        { name: 'Palau', code: 'PW' },
        { name: 'Palestinian Territory, Occupied', code: 'PS' },
        { name: 'Panama', code: 'PA' },
        { name: 'Papua New Guinea', code: 'PG' },
        { name: 'Paraguay', code: 'PY' },
        { name: 'Peru', code: 'PE' },
        { name: 'Philippines', code: 'PH' },
        { name: 'Pitcairn', code: 'PN' },
        { name: 'Poland', code: 'PL' },
        { name: 'Portugal', code: 'PT' },
        { name: 'Puerto Rico', code: 'PR' },
        { name: 'Qatar', code: 'QA' },
        { name: 'Reunion', code: 'RE' },
        { name: 'Romania', code: 'RO' },
        { name: 'Russian Federation', code: 'RU' },
        { name: 'RWANDA', code: 'RW' },
        { name: 'Saint Helena', code: 'SH' },
        { name: 'Saint Kitts and Nevis', code: 'KN' },
        { name: 'Saint Lucia', code: 'LC' },
        { name: 'Saint Pierre and Miquelon', code: 'PM' },
        { name: 'Saint Vincent and the Grenadines', code: 'VC' },
        { name: 'Samoa', code: 'WS' },
        { name: 'San Marino', code: 'SM' },
        { name: 'Sao Tome and Principe', code: 'ST' },
        { name: 'Saudi Arabia', code: 'SA' },
        { name: 'Senegal', code: 'SN' },
        { name: 'Serbia', code: 'RS' },
        { name: 'Seychelles', code: 'SC' },
        { name: 'Sierra Leone', code: 'SL' },
        { name: 'Singapore', code: 'SG' },
        { name: 'Slovakia', code: 'SK' },
        { name: 'Slovenia', code: 'SI' },
        { name: 'Solomon Islands', code: 'SB' },
        { name: 'Somalia', code: 'SO' },
        { name: 'South Africa', code: 'ZA' },
        { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
        { name: 'Spain', code: 'ES' },
        { name: 'Sri Lanka', code: 'LK' },
        { name: 'Sudan', code: 'SD' },
        { name: 'Suriname', code: 'SR' },
        { name: 'Svalbard and Jan Mayen', code: 'SJ' },
        { name: 'Swaziland', code: 'SZ' },
        { name: 'Sweden', code: 'SE' },
        { name: 'Switzerland', code: 'CH' },
        { name: 'Syrian Arab Republic', code: 'SY' },
        { name: 'Taiwan, Province of China', code: 'TW' },
        { name: 'Tajikistan', code: 'TJ' },
        { name: 'Tanzania, United Republic of', code: 'TZ' },
        { name: 'Thailand', code: 'TH' },
        { name: 'Timor-Leste', code: 'TL' },
        { name: 'Togo', code: 'TG' },
        { name: 'Tokelau', code: 'TK' },
        { name: 'Tonga', code: 'TO' },
        { name: 'Trinidad and Tobago', code: 'TT' },
        { name: 'Tunisia', code: 'TN' },
        { name: 'Turkey', code: 'TR' },
        { name: 'Turkmenistan', code: 'TM' },
        { name: 'Turks and Caicos Islands', code: 'TC' },
        { name: 'Tuvalu', code: 'TV' },
        { name: 'Uganda', code: 'UG' },
        { name: 'Ukraine', code: 'UA' },
        { name: 'United Arab Emirates', code: 'AE' },
        { name: 'United Kingdom', code: 'GB' },
        { name: 'United States', code: 'US' },
        { name: 'United States Minor Outlying Islands', code: 'UM' },
        { name: 'Uruguay', code: 'UY' },
        { name: 'Uzbekistan', code: 'UZ' },
        { name: 'Vanuatu', code: 'VU' },
        { name: 'Venezuela', code: 'VE' },
        { name: 'Viet Nam', code: 'VN' },
        { name: 'Virgin Islands, British', code: 'VG' },
        { name: 'Virgin Islands, U.S.', code: 'VI' },
        { name: 'Wallis and Futuna', code: 'WF' },
        { name: 'Western Sahara', code: 'EH' },
        { name: 'Yemen', code: 'YE' },
        { name: 'Zambia', code: 'ZM' },
        { name: 'Zimbabwe', code: 'ZW' },
      ]);
    } else {
      this.directionSubject.next(dir);
      this.countries.next(// All countries
      // length 252
       [
          {name: "أفغانستان",code: "AF"},
          {name: "جزر آلاند",code: "AX"},
          {name: "ألبانيا",code: "AL"},
          {name: "الجزائر",code: "DZ"},
          {name: "ساموا الأمريكية",code: "AS"},
          {name: "أندورا",code: "AD"},
          {name: "أنغولا",code: "AO"},
          {name: "أنغيلا",code: "AI"},
          {name: "أنتاركتيكا",code: "AQ"},
          {name: "أنتيغوا وبربودا",code: "AG"},
          {name: "الأرجنتين",code: "AR"},
          {name: "أرمينيا",code: "AM"},
          {name: "أروبا",code: "AW"},
          {name: "أستراليا",code: "AU"},
          {name: "النمسا",code: "AT"},
          {name: "أذربيجان",code: "AZ"},
          {name: "جزر البهاما",code: "BS"},
          {name: "البحرين",code: "BH"},
          {name: "بنغلاديش",code: "BD"},
          {name: "بربادوس",code: "BB"},
          {name: "بيلاروسيا",code: "BY"},
          {name: "بلجيكا",code: "BE"},
          {name: "بليز",code: "BZ"},
          {name: "بنين",code: "BJ"},
          {name: "برمودا",code: "BM"},
          {name: "بوتان",code: "BT"},
          {name: "بوليفيا",code: "BO"},
          {name: "بونير وسانت يوستاتيوس وسابا",code: "BQ"},
          {name: "البوسنة والهرسك",code: "BA"},
          {name: "بوتسوانا",code: "BW"},
          {name: "جزيرة بوفيت",code: "BV"},
          {name: "البرازيل",code: "BR"},
          {name: "إقليم المحيط البريطاني الهندي",code: "IO"},
          {name: "بروناي دار السلام",code: "BN"},
          {name: "بلغاريا",code: "BG"},
          {name: "بوركينا فاسو",code: "BF"},
          {name: "بوروندي",code: "BI"},
          {name: "كمبوديا",code: "KH"},
          {name: "الكاميرون",code: "CM"},
          {name: "كندا",code: "CA"},
          {name: "الرأس الأخضر",code: "CV"},
          {name: "جزر كايمان",code: "KY"},
          {name: "جمهورية افريقيا الوسطى",code: "CF"},
          {name: "تشاد",code: "TD"},
          {name: "تشيلي",code: "CL"},
          {name: "الصين",code: "CN"},
          {name: "جزيرة الكريسماس",code: "CX"},
          {name: "جزر كوكوس (كيلينغ)",code: "CC"},
          {name: "كولومبيا",code: "CO"},
          {name: "جزر القمر",code: "KM"},
          {name: "الكونغو",code: "CG"},
          {name: "الكونغو ، جمهورية الكونغو الديمقراطية",code: "CD"},
          {name: "جزر كوك",code: "CK"},
          {name: "كوستا ريكا",code: "CR"},
          {name: "ساحل العاج",code: "CI"},
          {name: "كرواتيا",code: "HR"},
          {name: "كوبا",code: "CU"},
          {name: "كوراكاو",code: "CW"},
          {name: "قبرص",code: "CY"},
          {name: "الجمهورية التشيكية",code: "CZ"},
          {name: "الدنمارك",code: "DK"},
          {name: "جيبوتي",code: "DJ"},
          {name: "دومينيكا",code: "DM"},
          {name: "جمهورية الدومنيكان",code: "DO"},
          {name: "الاكوادور",code: "EC"},
          {name: "مصر",code: "EG"},
          {name: "السلفادور",code: "SV"},
          {name: "غينيا الإستوائية",code: "GQ"},
          {name: "إريتريا",code: "ER"},
          {name: "إستونيا",code: "EE"},
          {name: "أثيوبيا",code: "ET"},
          {name: "جزر فوكلاند (مالفيناس)",code: "FK"},
          {name: "جزر فاروس",code: "FO"},
          {name: "فيجي",code: "FJ"},
          {name: "فنلندا",code: "FI"},
          {name: "فرنسا",code: "FR"},
          {name: "غيانا الفرنسية",code: "GF"},
          {name: "بولينيزيا الفرنسية",code: "PF"},
          {name: "المناطق الجنوبية لفرنسا",code: "TF"},
          {name: "الجابون",code: "GA"},
          {name: "غامبيا",code: "GM"},
          {name: "جورجيا",code: "GE"},
          {name: "ألمانيا",code: "DE"},
          {name: "غانا",code: "GH"},
          {name: "جبل طارق",code: "GI"},
          {name: "اليونان",code: "GR"},
          {name: "الأرض الخضراء",code: "GL"},
          {name: "غرينادا",code: "GD"},
          {name: "جوادلوب",code: "GP"},
          {name: "غوام",code: "GU"},
          {name: "غواتيمالا",code: "GT"},
          {name: "غيرنسي",code: "GG"},
          {name: "غينيا",code: "GN"},
          {name: "غينيا بيساو",code: "GW"},
          {name: "غيانا",code: "GY"},
          {name: "هايتي",code: "HT"},
          {name: "قلب الجزيرة وجزر ماكدونالز",code: "HM"},
          {name: "الكرسي الرسولي (دولة الفاتيكان)",code: "VA"},
          {name: "هندوراس",code: "HN"},
          {name: "هونج كونج",code: "HK"},
          {name: "هنغاريا",code: "HU"},
          {name: "أيسلندا",code: "IS"},
          {name: "الهند",code: "IN"},
          {name: "إندونيسيا",code: "ID"},
          {name: "جمهورية إيران الإسلامية",code: "IR"},
          {name: "العراق",code: "IQ"},
          {name: "أيرلندا",code: "IE"},
          {name: "جزيرة آيل أوف مان",code: "IM"},
          {name: "إسرائيل",code: "IL"},
          {name: "إيطاليا",code: "IT"},
          {name: "جامايكا",code: "JM"},
          {name: "اليابان",code: "JP"},
          {name: "جيرسي",code: "JE"},
          {name: "الأردن",code: "JO"},
          {name: "كازاخستان",code: "KZ"},
          {name: "كينيا",code: "KE"},
          {name: "كيريباتي",code: "KI"},
          {name: "كوريا، الجمهورية الشعبية الديمقراطية",code: "KP"},
          {name: "جمهورية كوريا",code: "KR"},
          {name: "كوسوفو",code: "XK"},
          {name: "الكويت",code: "KW"},
          {name: "قيرغيزستان",code: "KG"},
          {name: "جمهورية لاو الديمقراطية الشعبية",code: "LA"},
          {name: "لاتفيا",code: "LV"},
          {name: "لبنان",code: "LB"},
          {name: "ليسوتو",code: "LS"},
          {name: "ليبيريا",code: "LR"},
          {name: "الجماهيرية العربية الليبية",code: "LY"},
          {name: "ليختنشتاين",code: "LI"},
          {name: "ليتوانيا",code: "LT"},
          {name: "لوكسمبورغ",code: "LU"},
          {name: "ماكاو",code: "MO"},
          {name: "مقدونيا ، جمهورية يوغوسلافيا السابقة",code: "MK"},
          {name: "مدغشقر",code: "MG"},
          {name: "ملاوي",code: "MW"},
          {name: "ماليزيا",code: "MY"},
          {name: "جزر المالديف",code: "MV"},
          {name: "مالي",code: "ML"},
          {name: "مالطا",code: "MT"},
          {name: "جزر مارشال",code: "MH"},
          {name: "مارتينيك",code: "MQ"},
          {name: "موريتانيا",code: "MR"},
          {name: "موريشيوس",code: "MU"},
          {name: "مايوت",code: "YT"},
          {name: "المكسيك",code: "MX"},
          {name: "ولايات ميكرونيزيا الموحدة",code: "FM"},
          {name: "جمهورية مولدوفا",code: "MD"},
          {name: "موناكو",code: "MC"},
          {name: "منغوليا",code: "MN"},
          {name: "الجبل الأسود",code: "ME"},
          {name: "مونتسيرات",code: "MS"},
          {name: "المغرب",code: "MA"},
          {name: "موزمبيق",code: "MZ"},
          {name: "ميانمار",code: "MM"},
          {name: "ناميبيا",code: "NA"},
          {name: "ناورو",code: "NR"},
          {name: "نيبال",code: "NP"},
          {name: "هولندا",code: "NL"},
          {name: "جزر الأنتيل الهولندية",code: "AN"},
          {name: "كاليدونيا الجديدة",code: "NC"},
          {name: "نيوزيلاندا",code: "NZ"},
          {name: "نيكاراغوا",code: "NI"},
          {name: "النيجر",code: "NE"},
          {name: "نيجيريا",code: "NG"},
          {name: "نيوي",code: "NU"},
          {name: "جزيرة نورفولك",code: "NF"},
          {name: "جزر مريانا الشمالية",code: "MP"},
          {name: "النرويج",code: "NO"},
          {name: "سلطنة عمان",code: "OM"},
          {name: "باكستان",code: "PK"},
          {name: "بالاو",code: "PW"},
          {name: "الأراضي الفلسطينية المحتلة",code: "PS"},
          {name: "بنما",code: "PA"},
          {name: "بابوا غينيا الجديدة",code: "PG"},
          {name: "باراغواي",code: "PY"},
          {name: "بيرو",code: "PE"},
          {name: "فيلبيني",code: "PH"},
          {name: "بيتكيرن",code: "PN"},
          {name: "بولندا",code: "PL"},
          {name: "البرتغال",code: "PT"},
          {name: "بورتوريكو",code: "PR"},
          {name: "دولة قطر",code: "QA"},
          {name: "جمع شمل",code: "RE"},
          {name: "رومانيا",code: "RO"},
          {name: "الاتحاد الروسي",code: "RU"},
          {name: "رواندا",code: "RW"},
          {name: "سانت بارتيليمي",code: "BL"},
          {name: "سانت هيلانة",code: "SH"},
          {name: "سانت كيتس ونيفيس",code: "KN"},
          {name: "القديسة لوسيا",code: "LC"},
          {name: "القديس مارتن",code: "MF"},
          {name: "سانت بيير وميكلون",code: "PM"},
          {name: "سانت فنسنت وجزر غرينادين",code: "VC"},
          {name: "ساموا",code: "WS"},
          {name: "سان مارينو",code: "SM"},
          {name: "ساو تومي وبرينسيبي",code: "ST"},
          {name: "المملكة العربية السعودية",code: "SA"},
          {name: "السنغال",code: "SN"},
          {name: "صربيا",code: "RS"},
          {name: "صربيا والجبل الأسود",code: "CS"},
          {name: "سيشيل",code: "SC"},
          {name: "سيرا ليون",code: "SL"},
          {name: "سنغافورة",code: "SG"},
          {name: "سينت مارتن",code: "SX"},
          {name: "سلوفاكيا",code: "SK"},
          {name: "سلوفينيا",code: "SI"},
          {name: "جزر سليمان",code: "SB"},
          {name: "الصومال",code: "SO"},
          {name: "جنوب أفريقيا",code: "ZA"},
          {name: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",code: "GS"},
          {name: "جنوب السودان",code: "SS"},
          {name: "إسبانيا",code: "ES"},
          {name: "سيريلانكا",code: "LK"},
          {name: "السودان",code: "SD"},
          {name: "سورينام",code: "SR"},
          {name: "سفالبارد وجان ماين",code: "SJ"},
          {name: "سوازيلاند",code: "SZ"},
          {name: "السويد",code: "SE"},
          {name: "سويسرا",code: "CH"},
          {name: "الجمهورية العربية السورية",code: "SY"},
          {name: "مقاطعة تايوان الصينية",code: "TW"},
          {name: "طاجيكستان",code: "TJ"},
          {name: "جمهورية تنزانيا المتحدة",code: "TZ"},
          {name: "تايلاند",code: "TH"},
          {name: "تيمور ليشتي",code: "TL"},
          {name: "توجو",code: "TG"},
          {name: "توكيلاو",code: "TK"},
          {name: "تونغا",code: "TO"},
          {name: "ترينداد وتوباغو",code: "TT"},
          {name: "تونس",code: "TN"},
          {name: "ديك رومى",code: "TR"},
          {name: "تركمانستان",code: "TM"},
          {name: "جزر تركس وكايكوس",code: "TC"},
          {name: "توفالو",code: "TV"},
          {name: "أوغندا",code: "UG"},
          {name: "أوكرانيا",code: "UA"},
          {name: "الإمارات العربية المتحدة",code: "AE"},
          {name: "المملكة المتحدة",code: "GB"},
          {name: "الولايات المتحدة",code: "US"},
          {name: "جزر الولايات المتحدة البعيدة الصغرى",code: "UM"},
          {name: "أوروغواي",code: "UY"},
          {name: "أوزبكستان",code: "UZ"},
          {name: "فانواتو",code: "VU"},
          {name: "فنزويلا",code: "VE"},
          {name: "فييت نام",code: "VN"},
          {name: "جزر العذراء البريطانية",code: "VG"},
          {name: "جزر فيرجن ، الولايات المتحدة",code: "VI"},
          {name: "واليس وفوتونا",code: "WF"},
          {name: "الصحراء الغربية",code: "EH"},
          {name: "اليمن",code: "YE"},
          {name: "زامبيا",code: "ZM"},
          {name: "زيمبابوي",code: "ZW"}
      ])
    }

    // this.localEvent.next(lang)
  }

  scrollToTop(path: string): void {
    // Scroll to the top of the page
    window.scrollTo({ top: 0, behavior: 'smooth' });

    // Navigate to the specified route
    this._router.navigate([`/${path}`]);
  }
}
